<a href="https://colab.research.google.com/github/sonavmorris/DATASCIENCE-LAB/blob/main/LAB%201%20(04/08/22).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:

import numpy as np
my_list=([1,2,3],[4,5,6],[6,7,8])
np.arange(1,5)
np.arange(1,5,2)


array([1, 3])

In [6]:
np.array(my_list)

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [9]:
a=np.zeros((4,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [11]:
a=np.zeros((4,4))
a=a.astype(int)
print(a)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [13]:
np.ones(5)
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
np.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [17]:
np.random.rand(5)

array([0.62372076, 0.52995397, 0.79935601, 0.35388255, 0.20423802])

In [18]:
np.random.randn(5)

array([ 0.089638  ,  1.62744772,  0.42980374, -0.38267017, -0.49597986])

In [19]:
np.random.rand(4,4)

array([[0.88891695, 0.85460874, 0.5396355 , 0.72567692],
       [0.95036648, 0.21523908, 0.18425583, 0.7926273 ],
       [0.51497494, 0.39291438, 0.76366797, 0.63162234],
       [0.778408  , 0.81734278, 0.99767391, 0.1798874 ]])

In [20]:
np.random.randint(1,50)

23

In [21]:
np.random.randint(1,50,10)

array([ 2, 29, 17, 37, 48, 41, 29, 45, 35, 46])

In [23]:
array=([4,3,44,62,15,46,99,84,3,30])

In [28]:
arr=np.random.randint(1,100,10)
print(arr)
arr.shape

[10 82 58 56 61 39 68 13  7 38]


(10,)

In [29]:
arr.reshape(5,2)

array([[10, 82],
       [58, 56],
       [61, 39],
       [68, 13],
       [ 7, 38]])

In [30]:
arr.max()

82

In [31]:
arr.min()

7

In [32]:
arr.argmax()

1

In [33]:
arr.argmin()

8

In [34]:
arr_id=np.arange(0,10)

In [35]:
arr_id

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
arr_id[0:5]

array([0, 1, 2, 3, 4])

In [37]:
arr_id[:4]

array([0, 1, 2, 3])

In [38]:
arr_id[4:]

array([4, 5, 6, 7, 8, 9])

In [40]:
arr2=np.array([[1,2,3],[4,5,6],[6,7,8]])
print(arr2)

[[1 2 3]
 [4 5 6]
 [6 7 8]]


In [41]:
arr2[2]

array([6, 7, 8])

In [42]:
arr2[2,1]

7

In [44]:
arr2[0,0]

1

In [45]:
arr2[1:1]

array([], shape=(0, 3), dtype=int64)

In [47]:
arr2[:2,1:]

array([[2, 3],
       [5, 6]])

In [48]:
arr2[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
arr2[1:,:2]

array([[4, 5],
       [6, 7]])

In [52]:
ar=np.arange(5,15)

In [53]:
ar>8

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [54]:
bool_ar=ar>8

In [56]:
ar[bool_ar]

array([ 9, 10, 11, 12, 13, 14])

In [57]:
ar[ar>7]

array([ 8,  9, 10, 11, 12, 13, 14])

In [58]:
arr_new=np.arange(100).reshape(25,4)
print(arr_new)